const mathFields = [

    {
        id: 1,
        fieldName: 'Calculus',
        description: 'Focuses on derivatives and integrals for change analysis.',
        useCases: [
            'Modeling physical phenomena in physics',
            'Optimizing engineering designs',
            'Financial market predictions',
        ],
        topics: [
            'Limits and Continuity',
            'Differentiation Techniques',
            'Applications of Derivatives',
            'Integration Techniques',
            'Multivariable Calculus',
            'Differential Equations',
        ],
    },
    {
        id: 2,
        fieldName: 'Trigonometry',
        description: 'Studies relationships between triangle angles and sides.',
        useCases: [
            '3D modeling in computer graphics',
            'Acoustic engineering and sound design',
            'Satellite navigation systems',
        ],
        topics: [
            'Trigonometric Functions',
            'Graphs of Trigonometric Functions',
            'Trigonometric Identities and Equations',
            'Inverse Trigonometric Functions',
            'Applications of Trigonometry',
            'Spherical Trigonometry',
        ],
    },
    {
        id: 3,
        fieldName: 'Differential Equations',
        description: 'Models change with functions and derivatives.',
        useCases: [
            'Predicting disease spread in epidemiology',
            'Modeling electrical circuits',
            'Simulating natural processes in climate science',
        ],
        topics: [
            'First-Order Differential Equations',
            'Second-Order Differential Equations',
            'Partial Differential Equations',
            'Laplace Transforms',
            'Fourier Series and Transforms',
            'Nonlinear Differential Equations',
        ],
    },
    {
        id: 4,
        fieldName: 'Statistics',
        description: 'Involves data collection, analysis, and interpretation.',
        useCases: [
            'Data-driven decision making in business',
            'Predictive analytics in healthcare',
            'Machine learning model evaluation',
        ],
        topics: [
            'Descriptive Statistics',
            'Probability Distributions',
            'Statistical Inference',
            'Regression Analysis',
            'Bayesian Statistics',
            'Time Series Analysis',
        ],
    },

    {
        id: 5,
        fieldName: 'Linear Algebra',
        description: 'Studies vectors, matrices, and linear transformations.',
        useCases: [
            'Computer graphics and animation',
            'Machine learning algorithms',
            'Quantum computing advancements',
        ],
        topics: [
            'Vector Spaces',
            'Matrix Theory',
            'Linear Transformations',
            'Eigenvalues and Eigenvectors',
            'Diagonalization',
            'Orthogonality and Least Squares',
        ],
    },
    {
        id: 6,
        fieldName: 'Complex Analysis',
        description: 'Analyzes functions of complex numbers.',
        useCases: [
            'Signal processing in telecommunications',
            'Understanding fluid flows in aerodynamics',
            'Quantum mechanics and field theory',
        ],
        topics: [
            'Complex Numbers and Functions',
            'Analytic Functions',
            'Complex Integration',
            'Residue Theory',
            'Conformal Mapping',
            'Applications in Physics and Engineering',
        ],
    },
    {
        id: 7,
        fieldName: 'Vector Calculus',
        description: 'Deals with vector fields and operations.',
        useCases: [
            'Analyzing electromagnetic fields',
            'Simulating airflow over wings',
            'Modeling forces in mechanical systems',
        ],
        topics: [
            'Vector Fields',
            'Gradient, Divergence, and Curl',
            'Line and Surface Integrals',
            'Applications in Fluid Dynamics',
            'Applications in Electromagnetism',
        ],
    },
    {
        id: 8,
        fieldName: 'Game Theory',
        description: 'Studies strategic decision-making models.',
        useCases: [
            'Designing auction algorithms in economics',
            'Modeling competitive strategies in business',
            'Optimizing network security protocols',
        ],
        topics: [
            'Introduction to Game Theory',
            'Nash Equilibrium',
            'Cooperative Games',
            'Non-Cooperative Games',
            'Evolutionary Game Theory',
            'Applications in Economics and Politics',
        ],
    },
];

const scienceFields = [
    {
        id: 1,
        fieldName: 'Physics',
        description: 'Studies matter, energy, and their interactions.',
        useCases: [
            'Developing renewable energy technologies',
            'Advancements in quantum computing',
            'Medical technologies like MRI and PET scans',
        ],
        topics: [
            'Classical Mechanics',
            'Electromagnetism',
            'Thermodynamics',
            'Quantum Mechanics',
            'Relativity',
            'Astrophysics',
        ],
    },
    {
        id: 2,
        fieldName: 'Chemistry',
        description: 'Explores substances and their transformations.',
        useCases: [
            'Development of sustainable materials',
            'Pharmaceutical drug design',
            'Nanotechnology and materials science',
        ],
        topics: [
            'Organic Chemistry',
            'Inorganic Chemistry',
            'Physical Chemistry',
            'Analytical Chemistry',
            'Biochemistry',
            'Chemical Engineering',
        ],
    },
    {
        id: 3,
        fieldName: 'Biology',
        description: 'Examines living organisms and life processes.',
        useCases: [
            'Genomic research and personalized medicine',
            'Biotechnology and synthetic biology',
            'Conservation efforts and biodiversity studies',
        ],
        topics: [
            'Cell Biology',
            'Genetics',
            'Evolutionary Biology',
            'Ecology',
            'Molecular Biology',
            'Neuroscience',
        ],
    },
    {
        id: 4,
        fieldName: 'Astronomy',
        description: 'Studies celestial bodies and the universe.',
        useCases: [
            'Detection of exoplanets and astrobiology',
            'Cosmology and the study of dark matter',
            'Development of space exploration technologies',
        ],
        topics: [
            'Observational Astronomy',
            'Stellar Astronomy',
            'Galactic Astronomy',
            'Cosmology',
            'Astrobiology',
            'Exoplanet Research',
        ],
    },
    {
        id: 5,
        fieldName: 'Earth Science',
        description: 'Analyzes Earth’s structure and processes.',
        useCases: [
            'Climate change modeling and analysis',
            'Natural disaster prediction and management',
            'Resource exploration and sustainable mining',
        ],
        topics: [
            'Geology',
            'Meteorology',
            'Oceanography',
            'Seismology',
            'Volcanology',
            'Environmental Geoscience',
        ],
    },
    {
        id: 6,
        fieldName: 'Environmental Science',
        description: 'Focuses on human-environment interactions.',
        useCases: [
            'Sustainable agriculture and food systems',
            'Renewable energy and waste management',
            'Conservation and ecosystem restoration',
        ],
        topics: [
            'Ecology and Biodiversity',
            'Environmental Chemistry',
            'Climate Science',
            'Pollution Control',
            'Sustainable Development',
            'Environmental Policy and Management',
        ],
    },
    {
        id: 7,
        fieldName: 'Material Science',
        description: 'Studies properties of materials.',
        useCases: [
            'Development of advanced composites',
            'Biocompatible materials for medical use',
            'Innovative materials for electronics',
        ],
        topics: [
            'Solid State Physics',
            'Nanomaterials',
            'Metallurgy',
            'Polymers',
            'Ceramics',
            'Electronic Materials',
        ],
    },
];

const engineeringFields = [
    {
        id: 1,
        fieldName: 'Mechanical Engineering',
        description: 'Designs mechanical systems and machines.',
        useCases: [
            'Robotics and automation systems',
            'Renewable energy technologies',
            'Advanced manufacturing processes',
        ],
        topics: [
            'Thermodynamics',
            'Fluid Mechanics',
            'Materials Science',
            'Control Systems',
            'Robotics',
            'Manufacturing Processes',
        ],
    },
    {
        id: 2,
        fieldName: 'Aerospace Engineering',
        description: 'Focuses on aircraft and spacecraft design.',
        useCases: [
            'Designing next-generation aircraft',
            'Satellite technology and space exploration',
            'Development of hypersonic vehicles',
        ],
        topics: [
            'Fluid and Aerodynamics',
            'Propulsion Systems',
            'Flight Mechanics',
            'Spacecraft Design',
            'Avionics',
            'Aerospace Materials',
        ],
    },
    {
        id: 3,
        fieldName: 'Electrical Engineering',
        description: 'Studies electricity and electronics.',
        useCases: [
            'Development of smart grid technologies',
            'Design of integrated circuits and chips',
            'Advancements in wireless communication',
        ],
        topics: [
            'Circuit Analysis',
            'Electromagnetism',
            'Control Systems',
            'Digital Electronics',
            'Power Systems',
            'Signal Processing',
        ],
    },
    {
        id: 4,
        fieldName: 'Computer Science',
        description: 'Studies computation and software design.',
        useCases: [
            'Artificial intelligence and machine learning',
            'Blockchain and distributed systems',
            'Cybersecurity and data protection',
        ],
        topics: [
            'Algorithms and Data Structures',
            'Operating Systems',
            'Database Systems',
            'Computer Networks',
            'Machine Learning',
            'Software Engineering',
        ],
    },
    {
        id: 5,
        fieldName: 'Civil Engineering',
        description: 'Designs and constructs infrastructure.',
        useCases: [
            'Sustainable urban planning and development',
            'Smart city infrastructure and IoT integration',
            'Disaster-resilient building design',
        ],
        topics: [
            'Structural Analysis',
            'Geotechnical Engineering',
            'Transportation Engineering',
            'Water Resources Engineering',
            'Environmental Engineering',
            'Construction Management',
        ],
    },
    {
        id: 6,
        fieldName: 'Chemical Engineering',
        description: 'Designs chemical processes and products.',
        useCases: [
            'Renewable energy solutions',
            'Biochemical process development',
            'Advanced materials manufacturing',
        ],
        topics: [
            'Chemical Reaction Engineering',
            'Process Design and Control',
            'Thermodynamics',
            'Materials Science',
            'Biochemical Engineering',
            'Environmental Engineering',
        ],
    },
    {
        id: 7,
        fieldName: 'Biomedical Engineering',
        description: 'Develops healthcare technologies.',
        useCases: [
            'Development of wearable health monitors',
            'Tissue engineering and regenerative medicine',
            'Design of advanced prosthetics',
        ],
        topics: [
            'Biomaterials',
            'Medical Imaging',
            'Biomechanics',
            'Tissue Engineering',
            'Biomedical Instrumentation',
            'Rehabilitation Engineering',
        ],
    },
    {
        id: 8,
        fieldName: 'Industrial Engineering',
        description: 'Optimizes processes and systems.',
        useCases: [
            'Efficiency improvement in manufacturing',
            'Supply chain optimization',
            'Process automation and robotics',
        ],
        topics: [
            'Operations Research',
            'Quality Control',
            'Supply Chain Management',
            'Human Factors Engineering',
            'Manufacturing Systems',
            'Production Planning',
        ],
    },
    {
        id: 9,
        fieldName: 'Nuclear Engineering',
        description: 'Studies nuclear processes and applications.',
        useCases: [
            'Development of fusion energy technology',
            'Nuclear waste management solutions',
            'Radiation therapy advancements in medicine',
        ],
        topics: [
            'Nuclear Reactor Physics',
            'Radiation Protection',
            'Nuclear Fuel Cycle',
            'Radioactive Waste Management',
            'Nuclear Materials',
            'Medical Physics',
        ],
    },
    {
        id: 10,
        fieldName: 'Computer Engineering',
        description: 'Integrates hardware and software systems.',
        useCases: [
            'Design of embedded systems for IoT',
            'Development of computer hardware',
            'Artificial intelligence hardware solutions',
        ],
        topics: [
            'Embedded Systems',
            'Microprocessor Design',
            'Digital Signal Processing',
            'Computer Architecture',
            'VLSI Design',
            'Network Security',
        ],
    },
];

export { mathFields, scienceFields, engineeringFields };
